items:
- name: Azure’da Kubernetes
  href: ./index.yml
- name: Genel Bakış
  items:
  - name: Azure’da Kubernetes
    href: container-service-intro-kubernetes.md
- name: Hızlı Başlangıçlar
  items:
  - name: Azure’da Kubernetes
    href: container-service-kubernetes-walkthrough.md
  expanded: true
- name: Öğreticiler
  items:
  - name: 1 - Kapsayıcı görüntüleri oluşturma
    href: container-service-tutorial-kubernetes-prepare-app.md
  - name: 2 - Kapsayıcı kayıt defteri oluşturma
    href: container-service-tutorial-kubernetes-prepare-acr.md
  - name: 3 - Kubernetes kümesi oluşturma
    href: container-service-tutorial-kubernetes-deploy-cluster.md
  - name: 4 - Uygulamayı çalıştırma
    href: container-service-tutorial-kubernetes-deploy-application.md
  - name: 5 - Uygulamayı ölçeklendirme
    href: container-service-tutorial-kubernetes-scale.md
  - name: 6 - Uygulamayı güncelleştirme
    href: container-service-tutorial-kubernetes-app-update.md
  - name: 7 - Log Analytics ile izleme
    href: container-service-tutorial-kubernetes-monitor.md
- name: Kavramlar
  items:
  - name: Hizmet sorumlusu - Kubernetes
    href: container-service-kubernetes-service-principal.md
- name: Nasıl yapılır kılavuzları
  items:
  - name: Windows ile Kubernetes
    href: container-service-kubernetes-windows-walkthrough.md
  - name: Kubernetes web arabirimi
    href: container-service-kubernetes-ui.md
  - name: Helm grafiklerini kullanma
    href: container-service-kubernetes-helm.md
  - name: Azure Dosyaları ile verileri kalıcı hale getirme
    href: ../../aks/azure-files.md?toc=%2fazure%2fcontainer-service%2fkubernetes%2ftoc.json
  - name: ACS ile Draft kullanma
    href: container-service-draft-up.md
  - name: Küme ölçeklendirme
    href: container-service-scale.md
  - name: İzleme
    items:
    - name: Log Analytics ile izleme
      href: container-service-kubernetes-oms.md
    - name: Datadog ile izleme
      href: container-service-kubernetes-datadog.md
    - name: Sysdig ile izleme
      href: container-service-kubernetes-sysdig.md
    - name: CoScale ile izleme
      href: container-service-kubernetes-coscale.md
  - name: Spring Boot uygulamalarını dağıtma
    items:
    - name: Azure Container Service’te Linux üzerinde Spring Boot Uygulaması dağıtma
      href: container-service-deploy-spring-boot-app-on-linux.md
    - name: Azure Container Service’te bir Kubernetes Kümesi üzerinde Spring Boot Uygulaması dağıtma
      href: container-service-deploy-spring-boot-app-on-kubernetes.md
    - name: Fabric8 Maven eklentisi kullanarak Spring Boot uygulamasını dağıtma
      href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: Başvuru
  items:
  - name: Azure CLI
    href: /cli/azure/acs
  - name: PowerShell
    href: /powershell/module/az.compute
  - name: REST
    href: /rest/api/container-service
- name: Kaynaklar
  items:
  - name: Azure Yol Haritası
    href: https://azure.microsoft.com/roadmap/
  - name: SSS
    href: container-service-faq.md
  - name: Şablonlar - ACS Altyapısı
    href: https://github.com/Azure/acs-engine
  - name: Fiyatlandırma
    href: https://azure.microsoft.com/pricing/details/container-service/
  - name: Bölge kullanılabilirliği
    href: https://azure.microsoft.com/regions/services/
  - name: Stack Overflow
    href: https://stackoverflow.com/questions/tagged/azure-container-service
  - name: Videolar
    href: https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest
ms.openlocfilehash: 5761772088553029232eca9c8e0fe9ecff30fa43
ms.sourcegitcommit: 04716e13cc2ab69da57d61819da6cd5508f8c422
ms.translationtype: HT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/02/2019
ms.locfileid: "58850978"
